version: "3.8"
services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 20
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      TZ: Asia/Tokyo
      PGTZ: Asia/Tokyo

  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - "8080:8080"
    healthcheck:
      test: "curl -f http://localhost:8080 || exit 1"
      interval: 10s
      timeout: 3m
      retries: 20
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - type: bind
        source: .
        target: /go/src/app
      - type: volume
        source: app
        target: /go/pkg/mod

  frontend:
    build:
      context: ./frontend/my-app
      dockerfile: Dockerfile
    command: "npm run dev"
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3001:3000"
    depends_on:
      db:
        condition: service_healthy
      app:
        condition: service_healthy
    volumes:
      - type: bind
        source: ./frontend/my-app
        target: /app

volumes:
  db_data:
  app:
  frontend:
